---
new_page_extension: md
auto_deploy: false
admin_path: 
webhook_url: 
sections:
- path: site/content
  label: Pages
  create: all
- path: site/content/post
  label: Post
  create: all
upload_dir: site/static/uploads
public_path: "/uploads"
front_matter_path: ''
use_front_matter_path: false
file_template: ":filename:"
version: '0.43'
