baseURL = "https://tiagomadeira.com/"
languageCode = "pt-br"
title = "Tiago Madeira"
pygmentsCodeFences = true

[blackfriday]
  fractions = false

[params]
  description = "Um blog com pensamentos aleatórios principalmente sobre ciência da computação."

[taxonomies]
  categoria = "categorias"
