baseURL = "http://tmadeira.github.io/"
languageCode = "pt-br"
title = "Tiago Madeira"
pygmentsCodeFences = true

[blackfriday]
  fractions = false

[params]
  description = "Um blog com pensamentos aleatórios principalmente sobre ciência da computação."
