// @ts-nocheck
/* eslint-disable */
/* tslint:disable */
/* prettier-ignore-start */
/** @jsxRuntime classic */
/** @jsx createPlasmicElementProxy */
/** @jsxFrag React.Fragment */
// This class is auto-generated by Plasmic; please do not edit!
// Plasmic Project: oH8FCw6CW4Lg76cBx26GoT
// Component: VqtJtITmmH
import * as React from "react";
import {
  classNames,
  createPlasmicElementProxy,
  deriveRenderOpts,
} from "@plasmicapp/react-web";
import "@plasmicapp/react-web/lib/plasmic.css";
import "../plasmic__default_style.css"; // plasmic-import: global/defaultcss
import "./plasmic_site_layout.css"; // plasmic-import: oH8FCw6CW4Lg76cBx26GoT/projectcss
import "./PlasmicComments.css"; // plasmic-import: VqtJtITmmH/css

export const PlasmicComments__VariantProps = new Array();

export const PlasmicComments__ArgProps = new Array();

function PlasmicComments__RenderFunc(props) {
  const { variants, args, overrides, forNode } = props;
  return (
    <div
      data-plasmic-name={"root"}
      data-plasmic-override={overrides.root}
      data-plasmic-root={true}
      data-plasmic-for-node={forNode}
      className={classNames(
        "plasmic_default__all",
        "plasmic_default__div",
        "root_reset_oH8FCw6CW4Lg76cBx26GoT",
        "Comments__root__wtQdA"
      )}
    >
      <div
        data-plasmic-name={"box"}
        data-plasmic-override={overrides.box}
        className={classNames(
          "plasmic_default__all",
          "plasmic_default__div",
          "__wab_text",
          "Comments__box__dD6Fa"
        )}
      >
        {
          "O blog está temporariamente sem comentários. Em breve eles estarão de volta."
        }
      </div>
    </div>
  );
}

const PlasmicDescendants = {
  root: ["root", "box"],
  box: ["box"],
};

function makeNodeComponent(nodeName) {
  const func = function (props) {
    const { variants, args, overrides } = deriveRenderOpts(props, {
      name: nodeName,
      descendantNames: [...PlasmicDescendants[nodeName]],
      internalArgPropNames: PlasmicComments__ArgProps,
      internalVariantPropNames: PlasmicComments__VariantProps,
    });

    return PlasmicComments__RenderFunc({
      variants,
      args,
      overrides,
      forNode: nodeName,
    });
  };
  if (nodeName === "root") {
    func.displayName = "PlasmicComments";
  } else {
    func.displayName = `PlasmicComments.${nodeName}`;
  }
  return func;
}

export const PlasmicComments = Object.assign(
  // Top-level PlasmicComments renders the root element
  makeNodeComponent("root"),
  {
    // Helper components rendering sub-elements
    box: makeNodeComponent("box"),
    // Metadata about props expected for PlasmicComments
    internalVariantProps: PlasmicComments__VariantProps,
    internalArgProps: PlasmicComments__ArgProps,
  }
);

export default PlasmicComments;
/* prettier-ignore-end */
