// @ts-nocheck
/* eslint-disable */
/* tslint:disable */
/* prettier-ignore-start */
/** @jsxRuntime classic */
/** @jsx createPlasmicElementProxy */
/** @jsxFrag React.Fragment */
// This class is auto-generated by Plasmic; please do not edit!
// Plasmic Project: oH8FCw6CW4Lg76cBx26GoT
// Component: 7JhRlb0B4Y
import * as React from "react";
import * as p from "@plasmicapp/react-web";
import {
  classNames,
  createPlasmicElementProxy,
  deriveRenderOpts,
  ensureGlobalVariants,
} from "@plasmicapp/react-web";
import { useScreenVariants } from "../PlasmicGlobalVariant__Screen"; // plasmic-import: fOWX3a-rE7c/globalVariant
import "@plasmicapp/react-web/lib/plasmic.css";
import "../plasmic__default_style.css"; // plasmic-import: global/defaultcss
import "./plasmic_site_layout.css"; // plasmic-import: oH8FCw6CW4Lg76cBx26GoT/projectcss
import "./PlasmicBlockquote.css"; // plasmic-import: 7JhRlb0B4Y/css

export const PlasmicBlockquote__VariantProps = new Array();

export const PlasmicBlockquote__ArgProps = new Array("children");

function PlasmicBlockquote__RenderFunc(props) {
  const { variants, args, overrides, forNode } = props;
  const globalVariants = ensureGlobalVariants({
    screen: useScreenVariants(),
  });

  return (
    <p.Stack
      as={"blockquote"}
      data-plasmic-name={"root"}
      data-plasmic-override={overrides.root}
      data-plasmic-root={true}
      data-plasmic-for-node={forNode}
      hasGap={true}
      className={classNames(
        "plasmic_default__all",
        "plasmic_default__blockquote",
        "root_reset_oH8FCw6CW4Lg76cBx26GoT",
        "Blockquote__root___9Xne7"
      )}
    >
      <p.PlasmicSlot
        defaultContents={
          "Exemplo: Se há três mesas de credenciamento, pode-se atribuir a elas os intervalos letras A-I, J-R e S-Z. Nesse caso, alguém com um nome que comece com B (como Bruno) deve se credenciar na mesa A-I, enquanto alguém com um nome que comece com T (como Tiago) deve se credenciar na mesa S-Z."
        }
        value={args.children}
        className={classNames("Blockquote__slotChildren__qy49P")}
      />
    </p.Stack>
  );
}

const PlasmicDescendants = {
  root: ["root"],
};

function makeNodeComponent(nodeName) {
  const func = function (props) {
    const { variants, args, overrides } = deriveRenderOpts(props, {
      name: nodeName,
      descendantNames: [...PlasmicDescendants[nodeName]],
      internalArgPropNames: PlasmicBlockquote__ArgProps,
      internalVariantPropNames: PlasmicBlockquote__VariantProps,
    });

    return PlasmicBlockquote__RenderFunc({
      variants,
      args,
      overrides,
      forNode: nodeName,
    });
  };
  if (nodeName === "root") {
    func.displayName = "PlasmicBlockquote";
  } else {
    func.displayName = `PlasmicBlockquote.${nodeName}`;
  }
  return func;
}

export const PlasmicBlockquote = Object.assign(
  // Top-level PlasmicBlockquote renders the root element
  makeNodeComponent("root"),
  {
    // Helper components rendering sub-elements
    // Metadata about props expected for PlasmicBlockquote
    internalVariantProps: PlasmicBlockquote__VariantProps,
    internalArgProps: PlasmicBlockquote__ArgProps,
  }
);

export default PlasmicBlockquote;
/* prettier-ignore-end */
