/* eslint-disable */
/* tslint:disable */
/* prettier-ignore-start */
/** @jsx createPlasmicElementProxy */
// This class is auto-generated by Plasmic; please do not edit!
// Plasmic Project: oH8FCw6CW4Lg76cBx26GoT
// Component: 7JhRlb0B4Y
import * as React from "react";
import {
  classNames,
  Renderer,
  createPlasmicElementProxy,
  PlasmicSlot,
  deriveRenderOpts,
} from "@plasmicapp/react-web";
import { ScreenContext } from "../PlasmicGlobalVariant__Screen"; // plasmic-import: fOWX3a-rE7c/globalVariant
import "@plasmicapp/react-web/lib/plasmic.css";
import "../plasmic__default_style.css"; // plasmic-import: global/defaultcss
import "./plasmic_site_layout.css"; // plasmic-import: oH8FCw6CW4Lg76cBx26GoT/projectcss
import "./PlasmicBlockquote.css"; // plasmic-import: 7JhRlb0B4Y/css

export const PlasmicBlockquote__VariantProps = new Array();

export const PlasmicBlockquote__ArgProps = new Array("children");

function PlasmicBlockquote__RenderFunc(props) {
  const { variants, args, overrides, forNode } = props;
  const globalVariants = {
    screen: React.useContext(ScreenContext),
  };

  return (
    <blockquote
      data-plasmic-name={"root"}
      data-plasmic-override={overrides.root}
      data-plasmic-root={true}
      data-plasmic-for-node={forNode}
      data-plasmic-wrap-flex-child={true}
      className={classNames({
        "Blockquote__root--baseMedium__9XNE7P7WdO_MVUpr": true,
        Blockquote__root__9XNE7: true,
        "plasmic-default__all": true,
        "plasmic-default__blockquote": true,
      })}
    >
      <PlasmicSlot
        defaultContents={
          "Exemplo: Se há três mesas de credenciamento, pode-se atribuir a elas os intervalos letras A-I, J-R e S-Z. Nesse caso, alguém com um nome que comece com B (como Bruno) deve se credenciar na mesa A-I, enquanto alguém com um nome que comece com T (como Tiago) deve se credenciar na mesa S-Z.\n"
        }
        value={args.children}
        className={classNames({
          "Blockquote__slotChildren--baseMedium__qy49pP7WdO_MVUpr": true,
          Blockquote__slotChildren__qy49p: true,
        })}
      />
    </blockquote>
  );
}

class PlasmicBlockquote__Renderer extends Renderer {
  constructor(variants, args) {
    super(variants, args, PlasmicBlockquote__RenderFunc, "root");
  }
  create(variants, args) {
    return new PlasmicBlockquote__Renderer(variants, args);
  }
  getInternalVariantProps() {
    return PlasmicBlockquote__VariantProps;
  }
  getInternalArgProps() {
    return PlasmicBlockquote__ArgProps;
  }
  forNode(name) {
    return super.forNode(name);
  }
}

export const PlasmicBlockquote = function PlasmicBlockquoteRoot(props) {
  const { variants, args, overrides } = deriveRenderOpts(props, {
    name: "root",
    descendantNames: ["root"],
    internalArgPropNames: PlasmicBlockquote__ArgProps,
    internalVariantPropNames: PlasmicBlockquote__VariantProps,
  });

  return PlasmicBlockquote__RenderFunc({
    variants,
    args,
    overrides,
    forNode: "root",
  });
};

PlasmicBlockquote.createRenderer = () =>
  new PlasmicBlockquote__Renderer({}, {});

export default PlasmicBlockquote;
/* prettier-ignore-end */
