/* eslint-disable */
/* tslint:disable */
/* prettier-ignore-start */
/** @jsx createPlasmicElementProxy */
// This class is auto-generated by Plasmic; please do not edit!
// Plasmic Project: oH8FCw6CW4Lg76cBx26GoT
// Component: 2K6EDJzV0q
import * as React from "react";
import {
  classNames,
  Renderer,
  createPlasmicElementProxy,
  PlasmicSlot,
  deriveRenderOpts
} from "@plasmicapp/react-web";
import "@plasmicapp/react-web/lib/plasmic.css";
import "../plasmic__default_style.css"; // plasmic-import: global/defaultcss
import "./plasmic_site_layout.css"; // plasmic-import: oH8FCw6CW4Lg76cBx26GoT/projectcss
import "./PlasmicListItem.css"; // plasmic-import: 2K6EDJzV0q/css

export const PlasmicListItem__VariantProps = new Array();

export const PlasmicListItem__ArgProps = new Array(
  "title",
  "description",
  "subdescription",
  "subtitle",
  "badge"
);

function PlasmicListItem__RenderFunc(props) {
  const { variants, args, overrides, forNode } = props;
  return (
    <li
      data-plasmic-name={"root"}
      data-plasmic-override={overrides.root}
      data-plasmic-root={true}
      data-plasmic-for-node={forNode}
      data-plasmic-wrap-flex-child={true}
      className={classNames({
        ListItem__root__vQUdQ: true,
        "plasmic-default__all": true,
        "plasmic-default__li": true
      })}
    >
      <div
        data-plasmic-wrap-flex-child={true}
        className={classNames({
          ListItem__box__9E2uC: true,
          "plasmic-default__all": true,
          "plasmic-default__div": true
        })}
      >
        <PlasmicSlot
          defaultContents={"B.S. Computer Science"}
          value={args.title}
          className={classNames({
            "ListItem__slotTitle--baseMedium___nVULYrWvl_MVUpr": true,
            ListItem__slotTitle___nVUL: true
          })}
        />

        <div
          className={classNames({
            ListItem__box__e1X66: true,
            "plasmic-default__all": true,
            "plasmic-default__div": true
          })}
        >
          <PlasmicSlot
            defaultContents={
              <div
                className={classNames({
                  ListItem__box__IlrBF: true,
                  "plasmic-default__all": true,
                  "plasmic-default__div": true
                })}
              >
                <div
                  className={classNames({
                    ListItem__box__bJaJF: true,
                    "plasmic-default__all": true,
                    "plasmic-default__div": true
                  })}
                >
                  {"2016"}
                </div>
              </div>
            }
            value={args.badge}
          />
        </div>
      </div>

      <PlasmicSlot
        defaultContents={"University of São Paulo"}
        value={args.subtitle}
        className={classNames({
          "ListItem__slotSubtitle--baseMedium__OS36hYrWvl_MVUpr": true,
          ListItem__slotSubtitle__OS36h: true
        })}
      />

      <PlasmicSlot
        defaultContents={
          "Final project: Uniform sampling of k-trees for learning Bayesian networks"
        }
        value={args.description}
        className={classNames({
          "ListItem__slotDescription--baseMedium__EDhTxYrWvl_MVUpr": true,
          ListItem__slotDescription__EDhTx: true
        })}
      />

      <PlasmicSlot
        defaultContents={"Supervisor: Prof. Denis Deratani Maua"}
        value={args.subdescription}
        className={classNames({
          "ListItem__slotSubdescription--baseMedium__55Z1tYrWvl_MVUpr": true,
          ListItem__slotSubdescription__55Z1t: true
        })}
      />
    </li>
  );
}

class PlasmicListItem__Renderer extends Renderer {
  constructor(variants, args) {
    super(variants, args, PlasmicListItem__RenderFunc, "root");
  }
  create(variants, args) {
    return new PlasmicListItem__Renderer(variants, args);
  }
  getInternalVariantProps() {
    return PlasmicListItem__VariantProps;
  }
  getInternalArgProps() {
    return PlasmicListItem__ArgProps;
  }
  forNode(name) {
    return super.forNode(name);
  }
}

export const PlasmicListItem = function PlasmicListItemRoot(props) {
  const { variants, args, overrides } = deriveRenderOpts(props, {
    name: "root",
    descendantNames: ["root"],
    internalArgPropNames: PlasmicListItem__ArgProps,
    internalVariantPropNames: PlasmicListItem__VariantProps
  });

  return PlasmicListItem__RenderFunc({
    variants,
    args,
    overrides,
    forNode: "root"
  });
};

PlasmicListItem.createRenderer = () => new PlasmicListItem__Renderer({}, {});

export default PlasmicListItem;
/* prettier-ignore-end */
