/* eslint-disable */
/* tslint:disable */
/* prettier-ignore-start */
/** @jsx createPlasmicElementProxy */
// This class is auto-generated by Plasmic; please do not edit!
// Plasmic Project: oH8FCw6CW4Lg76cBx26GoT
// Component: 2K6EDJzV0q
import * as React from "react";
import {
  classNames,
  Renderer,
  createPlasmicElementProxy,
  PlasmicSlot,
  deriveRenderOpts
} from "@plasmicapp/react-web";
import "@plasmicapp/react-web/lib/plasmic.css";
import "../plasmic__default_style.css"; // plasmic-import: global/defaultcss
import "./plasmic_site_layout.css"; // plasmic-import: oH8FCw6CW4Lg76cBx26GoT/projectcss
import "./PlasmicSectionItem.css"; // plasmic-import: 2K6EDJzV0q/css

export const PlasmicSectionItem__VariantProps = new Array();

export const PlasmicSectionItem__ArgProps = new Array(
  "title",
  "description",
  "subdescription",
  "subtitle",
  "badge"
);

function PlasmicSectionItem__RenderFunc(props) {
  const { variants, args, overrides, forNode } = props;
  return (
    <div
      data-plasmic-name={"root"}
      data-plasmic-override={overrides.root}
      data-plasmic-root={true}
      data-plasmic-for-node={forNode}
      data-plasmic-wrap-flex-child={true}
      className={classNames({
        SectionItem__root__vQUdQ: true,
        "plasmic-default__all": true,
        "plasmic-default__div": true
      })}
    >
      <div
        data-plasmic-wrap-flex-child={true}
        className={classNames({
          SectionItem__box__9E2uC: true,
          "plasmic-default__all": true,
          "plasmic-default__div": true
        })}
      >
        <PlasmicSlot
          defaultContents={""}
          value={args.title}
          className={classNames({
            "SectionItem__slotTitle--baseMedium___nVULYrWvl_MVUpr": true,
            SectionItem__slotTitle___nVUL: true
          })}
        />

        <div
          className={classNames({
            SectionItem__box__e1X66: true,
            "plasmic-default__all": true,
            "plasmic-default__div": true
          })}
        >
          <PlasmicSlot defaultContents={undefined} value={args.badge} />
        </div>
      </div>

      <PlasmicSlot
        defaultContents={""}
        value={args.subtitle}
        className={classNames({
          "SectionItem__slotSubtitle--baseMedium__OS36hYrWvl_MVUpr": true,
          SectionItem__slotSubtitle__OS36h: true
        })}
      />

      <PlasmicSlot
        defaultContents={""}
        value={args.description}
        className={classNames({
          "SectionItem__slotDescription--baseMedium__EDhTxYrWvl_MVUpr": true,
          SectionItem__slotDescription__EDhTx: true
        })}
      />

      <PlasmicSlot
        defaultContents={""}
        value={args.subdescription}
        className={classNames({
          "SectionItem__slotSubdescription--baseMedium__55Z1tYrWvl_MVUpr": true,
          SectionItem__slotSubdescription__55Z1t: true
        })}
      />
    </div>
  );
}

class PlasmicSectionItem__Renderer extends Renderer {
  constructor(variants, args) {
    super(variants, args, PlasmicSectionItem__RenderFunc, "root");
  }
  create(variants, args) {
    return new PlasmicSectionItem__Renderer(variants, args);
  }
  getInternalVariantProps() {
    return PlasmicSectionItem__VariantProps;
  }
  getInternalArgProps() {
    return PlasmicSectionItem__ArgProps;
  }
  forNode(name) {
    return super.forNode(name);
  }
}

export const PlasmicSectionItem = function PlasmicSectionItemRoot(props) {
  const { variants, args, overrides } = deriveRenderOpts(props, {
    name: "root",
    descendantNames: ["root"],
    internalArgPropNames: PlasmicSectionItem__ArgProps,
    internalVariantPropNames: PlasmicSectionItem__VariantProps
  });

  return PlasmicSectionItem__RenderFunc({
    variants,
    args,
    overrides,
    forNode: "root"
  });
};

PlasmicSectionItem.createRenderer = () =>
  new PlasmicSectionItem__Renderer({}, {});

export default PlasmicSectionItem;
/* prettier-ignore-end */
